
spring:
  rabbitmq:
    # 如果配置其他虚拟主机地址，需要预先用管控台或者图形界面创建 图形界面地址 http://主机地址:15672
    addresses: localhost
    port: 5672
    # RabbitMQ 默认的用户名和密码都是guest 而虚拟主机名称是 "/"
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        # 为了保证信息能够被正确消费,建议签收模式设置为手工签收,并在代码中实现手工签收
        acknowledge-mode: manual
        # 侦听器调用者线程的最小数量
        concurrency: 10
        # 侦听器调用者线程的最大数量
        max-concurrency: 50
    #是否启用发布者确认 具体确认回调实现见代码
    publisher-confirms: true
    #是否启用发布者返回 具体返回回调实现见代码
    publisher-returns: true
    #是否启用强制消息 保证消息的有效监听
    template:
      mandatory: true

